[package]
name = "assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
base = {path = "../base" }

# Clap is dual-licensed MIT/Apache
# https://github.com/clap-rs/clap/blob/master/LICENSE-MIT
# https://github.com/clap-rs/clap/blob/master/LICENSE-APACHE
clap = "2"

# nom has an MIT-style copyright license.
# https://github.com/Geal/nom/blob/main/LICENSE
nom = "6"

# nom_locate has an MIT-style copyright license.
# https://github.com/fflorent/nom_locate/blob/master/LICENSE
nom_locate = "3"

# tracing has an MIT copyright license.
# https://github.com/tokio-rs/tracing/blob/master/LICENSE
tracing = "0.1"

# tracing-subscriber has an MIT copyright license.
# https://github.com/tokio-rs/tracing/blob/master/LICENSE
tracing-subscriber = "0.2"

[lib]
name = "assembler"
path = "src/asmlib/lib.rs"

[[bin]]
name = "tx2m4as"
path = "src/tx2m4as/main.rs"
