// Generated by @teamsupercell/typings-for-css-modules-loader
// Builds fail when this file is missing, which happens in CI pipelines; package.json just arranges for a second build which succeeds since the first creates this file.
declare namespace StylesScssNamespace {
  export interface IStylesScss {
    gridbox: string;
    instructions: string;
    io_panel: string;
    lw: string;
    lw__box: string;
    lw__cursor: string;
    lw__cursor_animation: string;
    lw__input__keyboard: string;
    lw__input__keyboard_hits: string;
    lw__input__keyboard_keys: string;
    lw__output: string;
    lw__output_container: string;
    lw__paper: string;
    main_grid_flexbox: string;
    status_panel: string;
    tape_load_modal__buttons: string;
  }
}

declare const StylesScssModule: StylesScssNamespace.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssNamespace.IStylesScss;
};

export = StylesScssModule;
