# Quickstart CI workflow
#
# This workflow installs latest stable Rust version
# and invokes these commands in parallel:
#
#  * `cargo check`
#  * `cargo test`
#  * [`cargo fmt`](https://github.com/rust-lang/rustfmt)
#  * [`cargo clippy`](https://github.com/rust-lang/rust-clippy)

on: [push, pull_request]

name: Continuous integration
permissions:
  contents: read

jobs:

  # These "X_and_Y" jobs each combine some steps that previously
  # existed in separate jobs, because combining them is more
  # resource-efficient.
  #
  # The two remaining jobs are still separate because it's useful to
  # be able easily to see that a change passes all tests but just has
  # clippy issues.

  build_and_test:
    # Combines previous Check, Build (stable), Test Suite (Rust stable)
    name: Check, Build and Test (Rust stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --workspace --all-features
      - run: cargo build --workspace --all-features
      - run: cargo test  --workspace --all-features

  fmt_and_clippy:
    # Combines previous Rustfmt (stable) and Clippy (stable) jobs
    name: Format and Lint Checks (Rust stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace -- -D warnings
