# Largely taken from
# https://github.com/dnaka91/advent-of-code/blob/82cc8bfb99f7ccf549b0baa624fe89b028c2c118/.github/workflows/docs.yml

name: Rust Docs
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust (nightly)
        # Use nightly in order to allow --enable-index-page below.
        uses: dtolnay/rust-toolchain@nightly
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Clean docs folder
        run: cargo clean --doc
      - name: Build docs
        # See
        # https://doc.rust-lang.org/beta/rustdoc/unstable-features.html#--index-page-provide-a-top-level-landing-page-for-docs
        # for documentation on rustdoc's --enable-index-page flag.
        run: cargo +nightly doc --document-private-items --no-deps -Z unstable-options --enable-index-page
      - name: Remove lock file
        run: rm target/doc/.lock
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
